name:       sqlite-binary-cache
version:    0.3.0.0
github:     jlavelle/sqlite-binary-cache
license:    MIT
author:     John C. Lavelle
maintainer: jlavelle604@gmail.com
copyright:  2021 John C. Lavelle
extra-source-files: test/*.golden

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >=4.13 && <4.14
  - bytestring
  - deepseq
  - foldl
  - neat-interpolation
  - profunctors
  - sqlite-simple
  - text
  - time
  - vector

library:
  source-dirs: src

tests:
  sqlite-binary-cache-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sqlite-binary-cache
      - containers
      - tasty
      - tasty-golden
      - tasty-hunit
